"""Core constants, errors, enums, tolerances, and unit helpers."""

from eie.core.enums import (
    BoundaryType,
    Carrier,
    MeasurementMethod,
    QualityGrade,
    Severity,
)
from eie.core.errors import (
    BoundaryError,
    DomainError,
    ExergyKernelError,
    MissingReferenceError,
    OffsetScaleError,
    PhysicsViolationError,
    StaleReferenceError,
    UnitError,
)
from eie.core.temperature import (
    AuditedTemperatureConverter,
    ConversionRecord,
    require_ratio_temperature,
    to_kelvin,
)
from eie.core.tolerance import DEFAULT_TOLERANCE, Tolerance
from eie.core.units import (
    CARBON_INTENSITY,
    DIMENSIONLESS,
    ENERGY,
    FREQUENCY,
    MASS,
    MASS_FLOW,
    POWER,
    PRESSURE,
    PRICE_PER_ENERGY,
    SPECIFIC_ENERGY,
    SPECIFIC_HEAT,
    TEMPERATURE,
    VOLTAGE,
    Dimension,
    Quantity,
    UnitDefinition,
    compatible_units,
    convert_value,
    dimension_for_unit,
    is_offset_scale_unit,
    require_dimension,
    require_same_dimension,
    require_unit,
    unit_is_known,
)

__all__ = [
    "AuditedTemperatureConverter",
    "BoundaryError",
    "BoundaryType",
    "CARBON_INTENSITY",
    "Carrier",
    "ConversionRecord",
    "DEFAULT_TOLERANCE",
    "DIMENSIONLESS",
    "Dimension",
    "DomainError",
    "ENERGY",
    "ExergyKernelError",
    "FREQUENCY",
    "MASS",
    "MASS_FLOW",
    "MeasurementMethod",
    "MissingReferenceError",
    "OffsetScaleError",
    "POWER",
    "PRESSURE",
    "PRICE_PER_ENERGY",
    "PhysicsViolationError",
    "QualityGrade",
    "Quantity",
    "SPECIFIC_ENERGY",
    "SPECIFIC_HEAT",
    "Severity",
    "StaleReferenceError",
    "TEMPERATURE",
    "Tolerance",
    "UnitDefinition",
    "UnitError",
    "VOLTAGE",
    "compatible_units",
    "convert_value",
    "dimension_for_unit",
    "is_offset_scale_unit",
    "require_dimension",
    "require_ratio_temperature",
    "require_same_dimension",
    "require_unit",
    "to_kelvin",
    "unit_is_known",
]
